# Generated by Django 3.2 on 2021-06-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField(db_index=True, verbose_name='Tweet ID')),
                ('full_text', models.CharField(max_length=280, verbose_name='Full Tweet Text')),
                ('num_retweets', models.IntegerField(db_index=True, verbose_name='Number of retweets')),
                ('num_likes', models.IntegerField(db_index=True, verbose_name='Number of likes')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['tweet_id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('display_url', models.CharField(max_length=128, verbose_name='Display URL')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='python_tips.tip')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
