# Generated by Django 3.2 on 2021-06-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_tips', '0002_alter_tip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
    ]
